# DATA NASA Final

In [1]:
import pandas as pd

# Nama file input
file_name = "datanasa.csv"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
# DIUBAH: Tambahkan sep=';' karena file Anda menggunakan titik koma
# DIUBAH: Tambahkan index_col=0 karena kolom pertama adalah indeks
df = pd.read_csv(file_name, sep=';', index_col=0)


# 3. Tampilkan beberapa baris pertama data asli (opsional)
file_name_to_display = "datanasa.csv"
df_to_display = pd.read_csv(file_name_to_display, sep=';')
print("\nMenampilkan beberapa baris pertama data awal dengan display():")
display(df_to_display.head())

# 4. Tentukan kolom target
# DIUBAH: Kita mencari .html di kolom 'url', bukan 'host'
target_column = "url"

# 5. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 6. Filter baris
    #    Logika ini sekarang akan diterapkan pada kolom 'url'
    print(f"\nMemfilter data untuk baris di mana '{target_column}' diakhiri dengan '.html'...")
    filtered_df = df[df[target_column].str.endswith('.html', na=False)].copy()

    # 7. Simpan data yang telah difilter ke file CSV baru
    output_filename = "html_requests_only_NASA.csv"
    # DIUBAH: Tambahkan sep=';' saat menyimpan agar konsisten
    filtered_df.to_csv(output_filename, sep=';')

    # 8. Cetak pesan sukses dan pratinjau data yang telah difilter
    file_name_to_display = "html_requests_only_NASA.csv"
    print(f"Memuat data dari {file_name_to_display} untuk ditampilkan...")
    df_to_display = pd.read_csv(file_name_to_display, sep=';')
    print("\nMenampilkan beberapa baris pertama dengan display():")
    display(df_to_display.head())

Memuat data dari datanasa.csv...

/tmp/ipython-input-705309671.py:10: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name, sep=';', index_col=0)
/tmp/ipython-input-705309671.py:15: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_to_display = pd.read_csv(file_name_to_display, sep=';')

Menampilkan beberapa baris pertama data awal dengan display():

,Unnamed: 0,host,time,method,url,response,bytes
0,0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,1,***.novo.dk,805465031,GET,/images/ksclogo-medium.gif,200,5866
2,2,***.novo.dk,805465051,GET,/images/MOSAIC-logosmall.gif,200,363
3,3,***.novo.dk,805465053,GET,/images/USA-logosmall.gif,200,234
4,4,***.novo.dk,805465054,GET,/images/NASA-logosmall.gif,200,786

Memfilter data untuk baris di mana 'url' diakhiri dengan '.html'...
Memuat data dari html_requests_only_NASA.csv untuk ditampilkan...

Menampilkan beberapa baris pertama dengan display():

/tmp/ipython-input-705309671.py:40: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_to_display = pd.read_csv(file_name_to_display, sep=';')

,Unnamed: 0,host,time,method,url,response,bytes
0,0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200,8678
2,12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200,6922
3,13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,11264
4,23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200,4665

In [2]:
from IPython.display import display

# Memuat kembali data yang sudah difilter untuk demonstrasi
file_name_to_display = "html_requests_only_NASA.csv"
print(f"Memuat data dari {file_name_to_display} untuk ditampilkan...")
df_to_display = pd.read_csv(file_name_to_display, sep=';')

print("\nMenampilkan beberapa baris pertama dengan display():")
display(df_to_display.head())

Memuat data dari html_requests_only_NASA.csv untuk ditampilkan...

Menampilkan beberapa baris pertama dengan display():

/tmp/ipython-input-38546358.py:6: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_to_display = pd.read_csv(file_name_to_display, sep=';')

,Unnamed: 0,host,time,method,url,response,bytes
0,0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200,8678
2,12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200,6922
3,13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,11264
4,23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200,4665

# Filter di ambil yang 200

In [3]:
import pandas as pd

# Nama file input (file dari langkah sebelumnya)
file_name = "html_requests_only_NASA.csv"

from IPython.display import display

# Memuat kembali data yang sudah difilter untuk demonstrasi
file_name_to_display = "html_requests_only_NASA.csv"
print(f"Memuat data dari {file_name_to_display} untuk ditampilkan...")
df_to_display = pd.read_csv(file_name_to_display, sep=';')

print("\nMenampilkan beberapa baris pertama dengan display():")
display(df_to_display.head())


# 2. Tentukan kolom target
target_column = "response"

# 3. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 4. Periksa apakah kolomnya numerik (sekarang seharusnya berhasil)
    if pd.api.types.is_numeric_dtype(df[target_column]):

        # 5. Filter baris di mana 'response' sama dengan 200
        print(f"\nMemfilter data untuk baris di mana '{target_column}' adalah 200...")

        # Ini adalah baris filter utama (logika Anda sudah benar)
        filtered_df = df[df[target_column] == 200].copy()

        # 6. Simpan data yang telah difilter ke file CSV baru
        output_filename = "status_200_only_NASA.csv"
        # DIUBAH: Tambahkan sep=';' agar konsisten saat menyimpan
        filtered_df.to_csv(output_filename, index=False, sep=';')



        # Memuat kembali data yang sudah difilter untuk demonstrasi
        file_name_to_display = "status_200_only_NASA.csv"
        print(f"Memuat data dari {file_name_to_display} untuk ditampilkan...")
        df_to_display = pd.read_csv(file_name_to_display, sep=';')

        print("\nMenampilkan beberapa baris pertama dengan display():")
        display(df_to_display.head())

Memuat data dari html_requests_only_NASA.csv untuk ditampilkan...

Menampilkan beberapa baris pertama dengan display():

/tmp/ipython-input-4186569879.py:11: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_to_display = pd.read_csv(file_name_to_display, sep=';')

,Unnamed: 0,host,time,method,url,response,bytes
0,0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200,8678
2,12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200,6922
3,13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,11264
4,23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200,4665

Memfilter data untuk baris di mana 'response' adalah 200...
Memuat data dari status_200_only_NASA.csv untuk ditampilkan...

Menampilkan beberapa baris pertama dengan display():

,host,time,method,url,response,bytes
0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,***.novo.dk,805465031,GET,/images/ksclogo-medium.gif,200,5866
2,***.novo.dk,805465051,GET,/images/MOSAIC-logosmall.gif,200,363
3,***.novo.dk,805465053,GET,/images/USA-logosmall.gif,200,234
4,***.novo.dk,805465054,GET,/images/NASA-logosmall.gif,200,786

# Filter ambil yang GET

In [4]:
import pandas as pd

# Nama file input (file dari langkah sebelumnya)
file_name = "status_200_only_NASA.csv"
filter_value = "GET"
# DIUBAH: Nama kolom yang benar adalah 'method', bukan 'Request method'
target_column = "method"

from IPython.display import display

# Memuat kembali data yang sudah difilter untuk demonstrasi
file_name_to_display = "status_200_only_NASA.csv"
print(f"Memuat data dari {file_name_to_display} untuk ditampilkan...")
df_to_display = pd.read_csv(file_name_to_display, sep=';')

print("\nMenampilkan beberapa baris pertama dengan display():")
display(df_to_display.head())



# 2. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 3. Filter baris di mana 'method' sama dengan 'GET'
    print(f"\nMemfilter data untuk baris di mana '{target_column}' adalah '{filter_value}'...")

    # Ini adalah baris filter utama (Logika Anda sudah benar)
    filtered_df = df[df[target_column] == filter_value].copy()

    # 4. Simpan data yang telah difilter ke file CSV baru
    output_filename = "method_get_only_NASA.csv"
    # DIUBAH: Tambahkan sep=';' agar konsisten saat menyimpan
    filtered_df.to_csv(output_filename, index=False, sep=';')


# Memuat kembali data yang sudah difilter untuk demonstrasi
file_name_to_display = "method_get_only_NASA.csv"
print(f"Memuat data dari {file_name_to_display} untuk ditampilkan...")
df_to_display = pd.read_csv(file_name_to_display, sep=';')

print("\nMenampilkan beberapa baris pertama dengan display():")
display(df_to_display.head())

Memuat data dari status_200_only_NASA.csv untuk ditampilkan...

Menampilkan beberapa baris pertama dengan display():

,host,time,method,url,response,bytes
0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,***.novo.dk,805465031,GET,/images/ksclogo-medium.gif,200,5866
2,***.novo.dk,805465051,GET,/images/MOSAIC-logosmall.gif,200,363
3,***.novo.dk,805465053,GET,/images/USA-logosmall.gif,200,234
4,***.novo.dk,805465054,GET,/images/NASA-logosmall.gif,200,786

Memfilter data untuk baris di mana 'method' adalah 'GET'...
Memuat data dari method_get_only_NASA.csv untuk ditampilkan...

Menampilkan beberapa baris pertama dengan display():

,host,time,method,url,response,bytes
0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,***.novo.dk,805465031,GET,/images/ksclogo-medium.gif,200,5866
2,***.novo.dk,805465051,GET,/images/MOSAIC-logosmall.gif,200,363
3,***.novo.dk,805465053,GET,/images/USA-logosmall.gif,200,234
4,***.novo.dk,805465054,GET,/images/NASA-logosmall.gif,200,786

# Ubah tanggal dan waktu ke DMY

In [5]:
import pandas as pd

# DIUBAH: Nama file input yang benar
file_name = "method_get_only_NASA.csv"
# DIUBAH: Nama kolom target yang benar
target_column = "time"

from IPython.display import display

# Memuat kembali data yang sudah difilter untuk demonstrasi
file_name_to_display = "method_get_only_NASA.csv"
print(f"Memuat data dari {file_name_to_display} untuk ditampilkan...")
df_to_display = pd.read_csv(file_name_to_display, sep=';')

print("\nMenampilkan beberapa baris pertama dengan display():")
display(df_to_display.head())

# 2. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 3. Tampilkan contoh format asli (ini adalah Angka/Timestamp)
    print(f"Format asli (baris pertama): {df[target_column].iloc[0]}")

    # 4. Lakukan transformasi:
    #    Kita tidak mengganti 'T' atau 'Z' karena data aslinya adalah angka (Unix timestamp).
    #    Kita akan MENGONVERSI timestamp itu ke format datetime yang mudah dibaca.
    print(f"Mengonversi kolom '{target_column}' (Unix timestamp) ke format Datetime...")

    # pd.to_datetime mengonversi angka timestamp (unit='s' berarti 'seconds')
    # Kita buat kolom baru 'datetime_readable' agar data asli tidak hilang
    df['datetime_readable'] = pd.to_datetime(df[target_column], unit='s')

    # 5. Simpan data yang telah diubah ke file CSV baru
    output_filename = "time_converted_NASA.csv"
    # DIUBAH: Tambahkan sep=';' agar konsisten
    df.to_csv(output_filename, index=False, sep=';')


# Memuat kembali data yang sudah difilter untuk demonstrasi
file_name_to_display = "time_converted_NASA.csv"
print(f"Memuat data dari {file_name_to_display} untuk ditampilkan...")
df_to_display = pd.read_csv(file_name_to_display, sep=';')

print("\nMenampilkan beberapa baris pertama dengan display():")
display(df_to_display.head())

Memuat data dari method_get_only_NASA.csv untuk ditampilkan...

Menampilkan beberapa baris pertama dengan display():

,host,time,method,url,response,bytes
0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,***.novo.dk,805465031,GET,/images/ksclogo-medium.gif,200,5866
2,***.novo.dk,805465051,GET,/images/MOSAIC-logosmall.gif,200,363
3,***.novo.dk,805465053,GET,/images/USA-logosmall.gif,200,234
4,***.novo.dk,805465054,GET,/images/NASA-logosmall.gif,200,786

Format asli (baris pertama): 805465029
Mengonversi kolom 'time' (Unix timestamp) ke format Datetime...
Memuat data dari time_converted_NASA.csv untuk ditampilkan...

Menampilkan beberapa baris pertama dengan display():

,host,time,method,url,response,bytes,datetime_readable
0,***.novo.dk,805465029,GET,/ksc.html,200,7067,1995-07-11 12:17:09
1,***.novo.dk,805465031,GET,/images/ksclogo-medium.gif,200,5866,1995-07-11 12:17:11
2,***.novo.dk,805465051,GET,/images/MOSAIC-logosmall.gif,200,363,1995-07-11 12:17:31
3,***.novo.dk,805465053,GET,/images/USA-logosmall.gif,200,234,1995-07-11 12:17:33
4,***.novo.dk,805465054,GET,/images/NASA-logosmall.gif,200,786,1995-07-11 12:17:34

# Filter berdasarkan IP addres

In [6]:
import pandas as pd

# 1. Tentukan file input (file yang memiliki 'datetime_readable')
file_name = "time_converted_NASA.csv"

# 2. Tentukan kolom-kolom yang akan kita gunakan
col_ip = "host"               # Kolom untuk mengelompokkan sesi
col_time = "datetime_readable" # Kolom untuk mengurutkan sesi
new_col_name = "SESSION"      # Nama kolom sesi baru

print(f"Memuat data dari {file_name}...")
try:
    # 3. Muat dataset
    # PENTING: Kita gunakan parse_dates=[col_time]
    # agar pandas langsung membacanya sebagai objek datetime
    df = pd.read_csv(file_name, sep=';', parse_dates=[col_time])
except FileNotFoundError:
    print(f"Error: File {file_name} tidak ditemukan.")
    print("Pastikan Anda sudah menjalankan skrip konversi 'time' sebelumnya.")
    exit()
except ValueError as e:
    print(f"Error saat membaca {file_name}. Cek kolom '{col_time}'.")
    print(f"Detail: {e}")
    exit()


# 4. Periksa apakah kolom yang diperlukan ada
if col_ip in df.columns and col_time in df.columns:

    # 5. BUAT KOLOM SESSION (Logika yang sama seperti sebelumnya)
    print(f"Membuat kolom '{new_col_name}' berdasarkan '{col_ip}' unik...")
    df[new_col_name] = df[col_ip].astype('category').cat.codes + 1

    # 6. Urutkan data berdasarkan SESSION, lalu WAKTU
    print(f"Mengurutkan data berdasarkan '{new_col_name}' dan '{col_time}'...")
    df_sorted = df.sort_values(by=[new_col_name, col_time], ascending=True)

    # 7. Hapus kolom 'time' (timestamp angka) yang asli agar rapi
    if 'time' in df_sorted.columns:
        print("Menghapus kolom 'time' (timestamp unix) asli...")
        df_sorted = df_sorted.drop(columns=['time'])

    # 8. Simpan DataFrame LENGKAP yang sudah diurutkan
    output_filename = "session_data_full_NASA.csv"

    # --- INI YANG DIUBAH ---
    # Kita ubah sep=';' (titik-koma) menjadi sep=',' (koma)
    print(f"Menyimpan data ke {output_filename} dengan pemisah KOMA (',')...")
    df_sorted.to_csv(output_filename, index=False, sep=',')
    # -------------------------

    print(f"\nBerhasil! Kolom '{new_col_name}' telah ditambahkan.")
    print(f"File baru disimpan sebagai: {output_filename}")
    print("\nPratinjau data baru (menampilkan kolom yang Anda minta):")

    # Tampilkan pratinjau hanya dengan kolom yang diminta agar mudah dilihat
    from IPython.display import display

    # Memuat kembali data yang sudah difilter untuk demonstrasi
    file_name_to_display = "status_200_only_NASA.csv"
    print(f"Memuat data dari {file_name_to_display} untuk ditampilkan...")
    df_to_display = pd.read_csv(file_name_to_display, sep=';')

    print("\nMenampilkan beberapa baris pertama dengan display():")
    display(df_to_display.head())

Memuat data dari time_converted_NASA.csv...
Membuat kolom 'SESSION' berdasarkan 'host' unik...
Mengurutkan data berdasarkan 'SESSION' dan 'datetime_readable'...
Menghapus kolom 'time' (timestamp unix) asli...
Menyimpan data ke session_data_full_NASA.csv dengan pemisah KOMA (',')...

Berhasil! Kolom 'SESSION' telah ditambahkan.
File baru disimpan sebagai: session_data_full_NASA.csv

Pratinjau data baru (menampilkan kolom yang Anda minta):
Memuat data dari status_200_only_NASA.csv untuk ditampilkan...

Menampilkan beberapa baris pertama dengan display():

,host,time,method,url,response,bytes
0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,***.novo.dk,805465031,GET,/images/ksclogo-medium.gif,200,5866
2,***.novo.dk,805465051,GET,/images/MOSAIC-logosmall.gif,200,363
3,***.novo.dk,805465053,GET,/images/USA-logosmall.gif,200,234
4,***.novo.dk,805465054,GET,/images/NASA-logosmall.gif,200,786

In [7]:
import pandas as pd

# 1. Tentukan file input (file yang memiliki 'datetime_readable')
file_name = "time_converted_NASA.csv"

# 2. Tentukan kolom-kolom yang akan kita gunakan
col_ip = "host"               # Kolom untuk mengelompokkan sesi
col_time = "datetime_readable" # Kolom untuk mengurutkan sesi
new_col_name = "SESSION"      # Nama kolom sesi baru

print(f"Memuat data dari {file_name}...")
try:
    # 3. Muat dataset (pemisah asli adalah ';')
    df = pd.read_csv(file_name, sep=';', parse_dates=[col_time])
except FileNotFoundError:
    print(f"Error: File {file_name} tidak ditemukan.")
    print("Pastikan Anda sudah menjalankan skrip konversi 'time' sebelumnya.")
    exit()
except ValueError as e:
    print(f"Error saat membaca {file_name}. Cek kolom '{col_time}'.")
    print(f"Detail: {e}")
    exit()


# 4. Periksa apakah kolom yang diperlukan ada
if col_ip in df.columns and col_time in df.columns:

    # 5. BUAT KOLOM SESSION (Logika yang sama seperti sebelumnya)
    print(f"Membuat kolom '{new_col_name}' berdasarkan '{col_ip}' unik...")
    df[new_col_name] = df[col_ip].astype('category').cat.codes + 1

    # 6. Urutkan data berdasarkan SESSION, lalu WAKTU
    print(f"Mengurutkan data berdasarkan '{new_col_name}' dan '{col_time}'...")
    df_sorted = df.sort_values(by=[new_col_name, col_time], ascending=True)

    # 7. (Langkah menghapus 'time' tidak diperlukan lagi)

    # --- DIUBAH DI SINI ---

    # 8. Tentukan kolom yang ingin disimpan (sesuai permintaan Anda)
    #    Kita tambahkan 'SESSION' ke daftar ini
    columns_to_keep = ['SESSION', 'host', 'datetime_readable', 'url']

    # Buat DataFrame baru HANYA dengan 4 kolom tersebut
    print(f"\nMemfilter data untuk HANYA menyimpan kolom: {columns_to_keep}...")
    df_final_output = df_sorted[columns_to_keep].copy()

    # 9. Simpan DataFrame yang SUDAH DIFILTER
    output_filename = "session_host_time_url_NASA.csv" # Nama file baru

    print(f"Menyimpan data ke {output_filename} dengan pemisah KOMA (',')...")
    df_final_output.to_csv(output_filename, index=False, sep=',')

    # -------------------------

    print(f"\nBerhasil! File baru disimpan sebagai: {output_filename}.")
    print("\nPratinjau data baru (sekarang dengan 4 kolom):")

    from IPython.display import display

    # Memuat kembali data yang sudah difilter untuk demonstrasi
    file_name_to_display = "session_host_time_url_NASA.csv"
    print(f"Memuat data dari {file_name_to_display} untuk ditampilkan...")
    # DIUBAH: Menggunakan sep=',' karena file disimpan dengan separator koma
    df_to_display = pd.read_csv(file_name_to_display, sep=',')

    print("\nMenampilkan beberapa baris pertama dengan display():")
    display(df_to_display.head(30))

Memuat data dari time_converted_NASA.csv...
Membuat kolom 'SESSION' berdasarkan 'host' unik...
Mengurutkan data berdasarkan 'SESSION' dan 'datetime_readable'...

Memfilter data untuk HANYA menyimpan kolom: ['SESSION', 'host', 'datetime_readable', 'url']...
Menyimpan data ke session_host_time_url_NASA.csv dengan pemisah KOMA (',')...

Berhasil! File baru disimpan sebagai: session_host_time_url_NASA.csv.

Pratinjau data baru (sekarang dengan 4 kolom):
Memuat data dari session_host_time_url_NASA.csv untuk ditampilkan...

Menampilkan beberapa baris pertama dengan display():

,SESSION,host,datetime_readable,url
0,1,***.novo.dk,1995-07-11 12:17:09,/ksc.html
1,1,***.novo.dk,1995-07-11 12:17:11,/images/ksclogo-medium.gif
2,1,***.novo.dk,1995-07-11 12:17:31,/images/MOSAIC-logosmall.gif
3,1,***.novo.dk,1995-07-11 12:17:33,/images/USA-logosmall.gif
4,1,***.novo.dk,1995-07-11 12:17:34,/images/NASA-logosmall.gif
5,1,***.novo.dk,1995-07-11 12:17:38,/images/WORLD-logosmall.gif
6,1,***.novo.dk,1995-07-11 12:17:48,/shuttle/missions/missions.html
7,1,***.novo.dk,1995-07-11 12:17:51,/images/launchmedium.gif
8,1,***.novo.dk,1995-07-11 12:19:13,/images/KSC-logosmall.gif
9,1,***.novo.dk,1995-07-11 12:19:17,/images/NASA-logosmall.gif
10,1,***.novo.dk,1995-07-11 12:22:03,/images/launch-logo.gif
11,1,***.novo.dk,1995-07-11 12:22:08,/history/apollo/images/apollo-logo1.gif
12,1,***.novo.dk,1995-07-11 12:23:01,/shuttle/resources/orbiters/columbia.html
13,1,***.novo.dk,1995-08-09 07:02:48,/shuttle/missions/sts-69/mission-sts-69.html
14,1,***.novo.dk,1995-08-09 07:02:55,/shuttle/missions/sts-69/sts-69-patch-small.gif
15,1,***.novo.dk,1995-08-09 07:03:02,/images/KSC-logosmall.gif
16,1,***.novo.dk,1995-08-09 07:03:06,/images/launch-logo.gif
17,1,***.novo.dk,1995-08-09 07:03:12,/history/apollo/images/apollo-logo1.gif
18,1,***.novo.dk,1995-08-09 07:03:52,/shuttle/countdown/
19,1,***.novo.dk,1995-08-09 07:04:08,/shuttle/missions/sts-69/count69.gif
20,1,***.novo.dk,1995-08-09 07:04:24,/images/NASA-logosmall.gif
21,1,***.novo.dk,1995-08-09 07:05:07,/htbin/cdt_main.pl
22,1,***.novo.dk,1995-08-09 07:05:14,/shuttle/countdown/images/countclock.gif
23,1,***.novo.dk,1995-08-09 07:05:38,/shuttle/countdown/liftoff.html
24,1,***.novo.dk,1995-08-09 07:06:21,/shuttle/countdown/video/livevideo2.gif
25,1,***.novo.dk,1995-08-09 07:07:24,/htbin/cdt_clock.pl
26,1,***.novo.dk,1995-08-09 07:07:40,/shuttle/countdown/lps/fr.html
27,1,***.novo.dk,1995-08-09 07:07:58,/shuttle/countdown/lps/fr.gif
28,1,***.novo.dk,1995-08-09 07:08:22,/shuttle/countdown/lps/back.gif
29,2,001.msy4.communique.net,1995-08-30 06:55:47,/software/winvn/winvn.html

# Final filter

In [8]:
import pandas as pd

# Nama file input
file_name = "session_host_time_url_NASA.csv"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")

# PERBAIKAN PENTING:
# File ini DISIMPAN dengan koma (',') → maka bacanya juga harus sep=','
df = pd.read_csv(file_name, sep=',')

# 4. Tentukan kolom target
target_column = "url"

# 5. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 6. Filter baris berdasarkan URL yang diakhiri ".html"
    print(f"\nMemfilter data untuk baris di mana '{target_column}' diakhiri dengan '.html'...")
    filtered_df = df[df[target_column].str.endswith('.html', na=False)].copy()

    # 7. Simpan data yang telah difilter ke file CSV baru
    output_filename = "final_filter_data_NASA.csv"

    # Simpan tetap pakai koma biar konsisten
    filtered_df.to_csv(output_filename, sep=',', index=False)

    from IPython.display import display

    # Memuat kembali data yang sudah difilter untuk ditampilkan
    file_name_to_display = "final_filter_data_NASA.csv"
    print(f"Memuat data dari {file_name_to_display} untuk ditampilkan...")

    df_to_display = pd.read_csv(file_name_to_display, sep=',')

    print("\nMenampilkan beberapa baris pertama dengan display():")
    display(df_to_display.head(30))

Memuat data dari session_host_time_url_NASA.csv...

Memfilter data untuk baris di mana 'url' diakhiri dengan '.html'...
Memuat data dari final_filter_data_NASA.csv untuk ditampilkan...

Menampilkan beberapa baris pertama dengan display():

,SESSION,host,datetime_readable,url
0,1,***.novo.dk,1995-07-11 12:17:09,/ksc.html
1,1,***.novo.dk,1995-07-11 12:17:48,/shuttle/missions/missions.html
2,1,***.novo.dk,1995-07-11 12:23:01,/shuttle/resources/orbiters/columbia.html
3,1,***.novo.dk,1995-08-09 07:02:48,/shuttle/missions/sts-69/mission-sts-69.html
4,1,***.novo.dk,1995-08-09 07:05:38,/shuttle/countdown/liftoff.html
5,1,***.novo.dk,1995-08-09 07:07:40,/shuttle/countdown/lps/fr.html
6,2,001.msy4.communique.net,1995-08-30 06:55:47,/software/winvn/winvn.html
7,3,007.thegap.com,1995-07-06 21:24:28,/shuttle/missions/sts-71/mission-sts-71.html
8,3,007.thegap.com,1995-07-06 21:28:35,/shuttle/missions/sts-71/mission-sts-71.html
9,3,007.thegap.com,1995-07-06 21:37:44,/shuttle/missions/sts-71/images/images.html
10,3,007.thegap.com,1995-07-06 23:23:26,/shuttle/countdown/tour.html
11,4,01-dynamic-c.wokingham.luna.net,1995-07-05 11:36:59,/shuttle/missions/sts-71/movies/movies.html
12,4,01-dynamic-c.wokingham.luna.net,1995-07-10 12:18:27,/history/history.html
13,4,01-dynamic-c.wokingham.luna.net,1995-07-10 12:18:57,/shuttle/missions/missions.html
14,4,01-dynamic-c.wokingham.luna.net,1995-07-12 09:33:34,/shuttle/missions/sts-71/mission-sts-71.html
15,4,01-dynamic-c.wokingham.luna.net,1995-07-27 21:02:24,/ksc.html
16,4,01-dynamic-c.wokingham.luna.net,1995-08-28 00:08:50,/shuttle/countdown/countdown.html
17,4,01-dynamic-c.wokingham.luna.net,1995-08-28 00:12:59,/shuttle/countdown/count.html
18,4,01-dynamic-c.wokingham.luna.net,1995-08-28 00:18:34,/shuttle/countdown/liftoff.html
19,4,01-dynamic-c.wokingham.luna.net,1995-08-28 00:36:38,/shuttle/countdown/lps/fr.html
20,4,01-dynamic-c.wokingham.luna.net,1995-08-28 00:37:22,/facilities/lcc.html
21,4,01-dynamic-c.wokingham.luna.net,1995-08-28 00:37:41,/facilities/tour.html
22,5,01.ts01.zircon.net.au,1995-08-21 08:46:06,/facts/faq04.html
23,6,02-17-05.comsvc.calpoly.edu,1995-08-28 15:03:26,/shuttle/missions/sts-65/mission-sts-65.html
24,7,02-dynamic-c.wokingham.luna.net,1995-07-07 11:59:10,/shuttle/missions/sts-68/ksc-srl-image.html
25,8,023.msy4.communique.net,1995-08-25 02:10:35,/shuttle/missions/sts-64/mission-sts-64.html
26,9,03-dynamic-c.wokingham.luna.net,1995-07-04 16:33:06,/shuttle/missions/sts-70/mission-sts-70.html
27,9,03-dynamic-c.wokingham.luna.net,1995-07-04 16:33:23,/shuttle/missions/sts-71/mission-sts-71.html
28,9,03-dynamic-c.wokingham.luna.net,1995-07-04 16:36:10,/shuttle/missions/sts-71/movies/movies.html
29,9,03-dynamic-c.wokingham.luna.net,1995-07-20 23:02:17,/shuttle/missions/sts-70/mission-sts-70.html

#Sesi

In [10]:
import pandas as pd

# Nama file input
file_name = "session_host_time_url_NASA.csv"

print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name, sep=',')

# 1. Hanya ambil baris dengan url berakhir .html
target_column = "url"

if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    print(f"\nMemfilter data untuk baris di mana '{target_column}' diakhiri dengan '.html'...")
    filtered_df = df[df[target_column].str.endswith('.html', na=False)].copy()

    # 2. Ubah kolom waktu ke datetime
    #    Sesuaikan nama kolom kalau beda (di screenshot: 'datetime_readable')
    filtered_df["datetime_readable"] = pd.to_datetime(filtered_df["datetime_readable"])

    # 3. Urutkan dulu berdasarkan host dan waktu
    filtered_df = filtered_df.sort_values(["host", "datetime_readable"])

    # 4. Buat kolom SESSION baru berdasarkan jeda > 1 menit per host
    session_threshold = pd.Timedelta(minutes=1)

    # diff() = selisih waktu dengan baris sebelumnya (untuk host yang sama)
    filtered_df["Sesi Login"] = (
        filtered_df
        .groupby("host")["datetime_readable"]
        .diff()                          # selisih waktu dengan baris sebelumnya
        .gt(session_threshold)           # True kalau selisih > 1 menit
        .fillna(True)                    # baris pertama tiap host dianggap sesi baru
        .groupby(filtered_df["host"])    # hitung kumulatif per host
        .cumsum()                        # 1,2,3,... per host
        .astype(int)
    )

    # Kalau kamu mau pakai nama kolom 'SESSION' saja (overwrite yang lama), bisa:
    # filtered_df.rename(columns={"SESSION_BARU": "SESSION"}, inplace=True)

    # 5. Simpan hasilnya
    output_filename = "final_filter_data_NASA_with_session.csv"
    filtered_df.to_csv(output_filename, sep=',', index=False)

    from IPython.display import display

    print(f"Memuat data dari {output_filename} untuk ditampilkan...")
    df_to_display = pd.read_csv(output_filename, sep=',')

    print("\nMenampilkan beberapa baris pertama dengan display():")
    display(df_to_display.head(30))

Memuat data dari session_host_time_url_NASA.csv...

Memfilter data untuk baris di mana 'url' diakhiri dengan '.html'...
Memuat data dari final_filter_data_NASA_with_session.csv untuk ditampilkan...

Menampilkan beberapa baris pertama dengan display():

,SESSION,host,datetime_readable,url,Sesi Login
0,1,***.novo.dk,1995-07-11 12:17:09,/ksc.html,0
1,1,***.novo.dk,1995-07-11 12:17:48,/shuttle/missions/missions.html,0
2,1,***.novo.dk,1995-07-11 12:23:01,/shuttle/resources/orbiters/columbia.html,1
3,1,***.novo.dk,1995-08-09 07:02:48,/shuttle/missions/sts-69/mission-sts-69.html,2
4,1,***.novo.dk,1995-08-09 07:05:38,/shuttle/countdown/liftoff.html,3
5,1,***.novo.dk,1995-08-09 07:07:40,/shuttle/countdown/lps/fr.html,4
6,2,001.msy4.communique.net,1995-08-30 06:55:47,/software/winvn/winvn.html,0
7,3,007.thegap.com,1995-07-06 21:24:28,/shuttle/missions/sts-71/mission-sts-71.html,0
8,3,007.thegap.com,1995-07-06 21:28:35,/shuttle/missions/sts-71/mission-sts-71.html,1
9,3,007.thegap.com,1995-07-06 21:37:44,/shuttle/missions/sts-71/images/images.html,2
10,3,007.thegap.com,1995-07-06 23:23:26,/shuttle/countdown/tour.html,3
11,4,01-dynamic-c.wokingham.luna.net,1995-07-05 11:36:59,/shuttle/missions/sts-71/movies/movies.html,0
12,4,01-dynamic-c.wokingham.luna.net,1995-07-10 12:18:27,/history/history.html,1
13,4,01-dynamic-c.wokingham.luna.net,1995-07-10 12:18:57,/shuttle/missions/missions.html,1
14,4,01-dynamic-c.wokingham.luna.net,1995-07-12 09:33:34,/shuttle/missions/sts-71/mission-sts-71.html,2
15,4,01-dynamic-c.wokingham.luna.net,1995-07-27 21:02:24,/ksc.html,3
16,4,01-dynamic-c.wokingham.luna.net,1995-08-28 00:08:50,/shuttle/countdown/countdown.html,4
17,4,01-dynamic-c.wokingham.luna.net,1995-08-28 00:12:59,/shuttle/countdown/count.html,5
18,4,01-dynamic-c.wokingham.luna.net,1995-08-28 00:18:34,/shuttle/countdown/liftoff.html,6
19,4,01-dynamic-c.wokingham.luna.net,1995-08-28 00:36:38,/shuttle/countdown/lps/fr.html,7
20,4,01-dynamic-c.wokingham.luna.net,1995-08-28 00:37:22,/facilities/lcc.html,7
21,4,01-dynamic-c.wokingham.luna.net,1995-08-28 00:37:41,/facilities/tour.html,7
22,5,01.ts01.zircon.net.au,1995-08-21 08:46:06,/facts/faq04.html,0
23,6,02-17-05.comsvc.calpoly.edu,1995-08-28 15:03:26,/shuttle/missions/sts-65/mission-sts-65.html,0
24,7,02-dynamic-c.wokingham.luna.net,1995-07-07 11:59:10,/shuttle/missions/sts-68/ksc-srl-image.html,0
25,8,023.msy4.communique.net,1995-08-25 02:10:35,/shuttle/missions/sts-64/mission-sts-64.html,0
26,9,03-dynamic-c.wokingham.luna.net,1995-07-04 16:33:06,/shuttle/missions/sts-70/mission-sts-70.html,0
27,9,03-dynamic-c.wokingham.luna.net,1995-07-04 16:33:23,/shuttle/missions/sts-71/mission-sts-71.html,0
28,9,03-dynamic-c.wokingham.luna.net,1995-07-04 16:36:10,/shuttle/missions/sts-71/movies/movies.html,1
29,9,03-dynamic-c.wokingham.luna.net,1995-07-20 23:02:17,/shuttle/missions/sts-70/mission-sts-70.html,2

# Buat Abjad berdasarkan html unik

In [11]:
from string import ascii_uppercase

# daftar huruf A-Z
letters = list(ascii_uppercase)

def assign_letter_per_host(group):
    # Ambil URL unik per host, urut sesuai kemunculan pertama
    unique_urls = group["url"].drop_duplicates()

    if len(unique_urls) > len(letters):
        print(f"Peringatan: host {group['host'].iloc[0]} punya lebih dari 26 halaman unik. "
              f"Hanya 26 pertama yang akan diberi huruf A-Z.")

    # Buat mapping: url -> huruf (A, B, C, ...)
    url_to_letter = {
        url: letters[i]
        for i, url in enumerate(unique_urls)
        if i < len(letters)              # jaga-jaga kalau >26
    }

    # Tambahkan kolom baru berisi huruf
    group["url_code"] = group["url"].map(url_to_letter)

    return group

# Terapkan per host
filtered_df = (
    filtered_df
    .sort_values(["host", "datetime_readable"])     # pastikan terurut dulu
    .groupby("host", group_keys=False)
    .apply(assign_letter_per_host)
)

# Kalau mau, kamu bisa drop kolom 'url' lama dan ganti jadi huruf,
# tapi biasanya lebih aman disimpan dua-duanya.
# Misalnya:
# filtered_df["url_asli"] = filtered_df["url"]
# filtered_df["url"] = filtered_df["url_code"]

# Simpan ke file baru
output_with_letters = "final_filter_data_NASA_with_session_and_letters.csv"
filtered_df.to_csv(output_with_letters, sep=",", index=False)

from IPython.display import display
print(f"\nMenampilkan beberapa baris pertama dengan kode huruf per host:")
display(filtered_df.head(30))

Peringatan: host 128.115.70.241 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 128.158.54.14 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 128.159.123.58 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 128.159.76.128 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 128.163.196.12 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 128.176.0.7 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 128.217.62.2 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 128.217.62.224 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 128.217.62.81 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 128.220.116.211 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 128.230.4.244 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 128.252.178.177 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 128.253.187.17 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 129.188.154.200 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 129.30.54.148 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 129.50.20.10 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 129.89.71.246 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 130.103.48.217 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 130.109.116.175 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 130.110.74.81 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 130.132.25.94 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 131.115.64.91 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 131.158.54.104 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 131.182.28.171 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 131.235.106.201 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 133.53.64.33 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 134.186.196.66 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 134.39.177.135 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 136.205.215.176 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 137.226.108.22 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 137.78.253.187 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 140.229.116.37 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 141.102.80.167 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 142.12.9.52 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 142.139.26.142 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 144.252.16.54 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 147.147.191.43 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 147.151.1.168 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 149.23.173.12 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 150.18.48.11 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 152.11.249.48 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 152.163.192.3 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 152.163.192.35 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 152.163.192.36 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 152.163.192.38 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 152.163.192.5 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 152.163.192.66 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 152.163.192.67 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 152.163.192.7 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 152.163.192.70 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 152.163.192.71 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 152.52.6.79 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 152.85.3.3 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 153.103.3.51 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 155.218.56.241 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 156.63.85.190 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 158.152.1.40 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 158.27.59.88 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 160.205.119.27 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 161.187.78.21 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 161.40.39.49 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 162.41.101.6 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 163.205.1.19 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 163.205.1.45 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 163.205.12.166 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 163.205.180.17 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 163.206.137.21 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 163.206.140.4 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 163.206.89.4 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 163.234.140.22 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 164.156.73.54 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 164.71.1.130 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 165.103.5.123 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 165.113.8.96 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 165.152.162.26 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 165.79.84.43 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 168.239.2.116 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 192.160.116.130 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 192.167.190.49 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 192.203.159.146 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 192.223.3.88 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 192.58.206.21 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 192.71.102.2 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 192.77.52.12 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 193.132.114.242 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 193.178.53.180 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 193.88.52.137 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 194.81.170.1 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 196.7.2.49 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 198.102.88.3 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 198.133.29.18 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 198.14.55.105 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 198.213.130.39 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 198.72.41.51 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 198.76.200.3 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 198.83.19.40 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 198.83.19.42 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 198.83.19.43 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 198.83.19.44 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 198.83.19.47 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 198.93.136.116 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 199-186.ico.att.net punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 199.1.50.225 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 199.1.60.95 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 199.10.135.154 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 199.125.188.19 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 199.17.85.174 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 199.201.186.102 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 199.201.186.103 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 199.201.186.105 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 199.75.171.163 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 199.93.170.211 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 202.239.48.3 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 202.49.41.122 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 203.255.208.24 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 204.148.101.58 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 204.158.58.1 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 204.179.186.33 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 204.181.236.201 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 204.62.245.32 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 204.69.0.27 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 205.139.153.28 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 205.184.202.5 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 205.206.73.149 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 205.216.162.12 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 206.23.2.202 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 206.27.25.1 punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host 400gtw.nl punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host a2014.dial.tip.net punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host abadon.stm.it punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host abrams-lr-kfps-dynamic-87.stanford.edu punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host abyss.sni-usa.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host acmex.gatech.edu punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host ad02-010.compuserve.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host ad03-022.compuserve.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host ad09-019.compuserve.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host adinet.analog.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host advantis.vnet.ibm.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host aero.snds.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host agora.carleton.ca punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host aheil_pc.orem.novell.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host ainet.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host algol.ksc.nasa.gov punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host alianza.letts.american.edu punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host alice-thurman.tenet.edu punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host alize.ere.umontreal.ca punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host allisontp.laafb.af.mil punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host alyssa.prodigy.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host amdext.amd.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host annex6-61.dial.umd.edu punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host anomaly.bu.edu punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host anonymous.chevron.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host apci.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host apxtg01.apex.dg.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host arc.dental.upenn.edu punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host arcada.arcada.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host arctic.nad.northrop.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host arena.carleton.ca punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host ariel.earth.nwu.edu punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host aristotle.algonet.se punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host art.mindspring.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host arthur.intel.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host artsnew21.usask.ca punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host asbestos.cacd.rockwell.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host aset.rsoc.rockwell.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host asgard.aecl.ntt.jp punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host asky.picky.or.jp punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host asp.erinet.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host astarte.mch.sni.de punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host astro.ocis.temple.edu punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host atc.eag.unisysgsg.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host ath-gw7.hol.gr punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host athos.astro.sp-agency.ca punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host atlas.fiu.edu punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host atluw02.dbsoftware.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host atropos.jf.intel.com punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host auriga.db.erau.edu punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.
Peringatan: host aztec.asu.edu punya lebih dari 26 halaman unik. Hanya 26 pertama yang akan diberi huruf A-Z.

/tmp/ipython-input-1846060749.py:31: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(assign_letter_per_host)

Menampilkan beberapa baris pertama dengan kode huruf per host:

,SESSION,host,datetime_readable,url,Sesi Login,url_code
0,1,***.novo.dk,1995-07-11 12:17:09,/ksc.html,0,A
6,1,***.novo.dk,1995-07-11 12:17:48,/shuttle/missions/missions.html,0,B
12,1,***.novo.dk,1995-07-11 12:23:01,/shuttle/resources/orbiters/columbia.html,1,C
13,1,***.novo.dk,1995-08-09 07:02:48,/shuttle/missions/sts-69/mission-sts-69.html,2,D
23,1,***.novo.dk,1995-08-09 07:05:38,/shuttle/countdown/liftoff.html,3,E
26,1,***.novo.dk,1995-08-09 07:07:40,/shuttle/countdown/lps/fr.html,4,F
29,2,001.msy4.communique.net,1995-08-30 06:55:47,/software/winvn/winvn.html,0,A
41,3,007.thegap.com,1995-07-06 21:24:28,/shuttle/missions/sts-71/mission-sts-71.html,0,A
44,3,007.thegap.com,1995-07-06 21:28:35,/shuttle/missions/sts-71/mission-sts-71.html,1,A
46,3,007.thegap.com,1995-07-06 21:37:44,/shuttle/missions/sts-71/images/images.html,2,B
52,3,007.thegap.com,1995-07-06 23:23:26,/shuttle/countdown/tour.html,3,C
71,4,01-dynamic-c.wokingham.luna.net,1995-07-05 11:36:59,/shuttle/missions/sts-71/movies/movies.html,0,A
80,4,01-dynamic-c.wokingham.luna.net,1995-07-10 12:18:27,/history/history.html,1,B
83,4,01-dynamic-c.wokingham.luna.net,1995-07-10 12:18:57,/shuttle/missions/missions.html,1,C
85,4,01-dynamic-c.wokingham.luna.net,1995-07-12 09:33:34,/shuttle/missions/sts-71/mission-sts-71.html,2,D
90,4,01-dynamic-c.wokingham.luna.net,1995-07-27 21:02:24,/ksc.html,3,E
99,4,01-dynamic-c.wokingham.luna.net,1995-08-28 00:08:50,/shuttle/countdown/countdown.html,4,F
102,4,01-dynamic-c.wokingham.luna.net,1995-08-28 00:12:59,/shuttle/countdown/count.html,5,G
104,4,01-dynamic-c.wokingham.luna.net,1995-08-28 00:18:34,/shuttle/countdown/liftoff.html,6,H
105,4,01-dynamic-c.wokingham.luna.net,1995-08-28 00:36:38,/shuttle/countdown/lps/fr.html,7,I
111,4,01-dynamic-c.wokingham.luna.net,1995-08-28 00:37:22,/facilities/lcc.html,7,J
115,4,01-dynamic-c.wokingham.luna.net,1995-08-28 00:37:41,/facilities/tour.html,7,K
126,5,01.ts01.zircon.net.au,1995-08-21 08:46:06,/facts/faq04.html,0,A
130,6,02-17-05.comsvc.calpoly.edu,1995-08-28 15:03:26,/shuttle/missions/sts-65/mission-sts-65.html,0,A
140,7,02-dynamic-c.wokingham.luna.net,1995-07-07 11:59:10,/shuttle/missions/sts-68/ksc-srl-image.html,0,A
144,8,023.msy4.communique.net,1995-08-25 02:10:35,/shuttle/missions/sts-64/mission-sts-64.html,0,A
145,9,03-dynamic-c.wokingham.luna.net,1995-07-04 16:33:06,/shuttle/missions/sts-70/mission-sts-70.html,0,A
149,9,03-dynamic-c.wokingham.luna.net,1995-07-04 16:33:23,/shuttle/missions/sts-71/mission-sts-71.html,0,B
155,9,03-dynamic-c.wokingham.luna.net,1995-07-04 16:36:10,/shuttle/missions/sts-71/movies/movies.html,1,C
157,9,03-dynamic-c.wokingham.luna.net,1995-07-20 23:02:17,/shuttle/missions/sts-70/mission-sts-70.html,2,A

# Tabel Kunjungan Tiap host

In [18]:
import pandas as pd

# pakai dataframe yang sudah ada url_code & sesi
df = filtered_df.copy()

# --- 1. Nama kolom sesi (ganti kalau beda) ---
session_col = "Sesi Login"   # kalau punyamu 'SESSION', ganti ke "SESSION"

# --- 2. Tambah kolom 'visited' berisi 1 ---
df["visited"] = 1

# --- 3. Pivot: 1 baris = host + sesi ---
wide_df = (
    df
    .pivot_table(
        index=["host", session_col],   # baris: per host per sesi
        columns="url_code",            # kolom: A, B, C, ...
        values="visited",
        aggfunc="max",                 # kalau ada beberapa baris, tetap 1
        fill_value=0                   # yang tidak dikunjungi → 0
    )
    .reset_index()
)

# hilangkan nama level kolom bawaan pivot_table
wide_df.columns.name = None

# --- 4. Simpan ke CSV baru ---
output_wide = "tabel_sesi_per_host.csv"
wide_df.to_csv(output_wide, sep=",", index=False)

from IPython.display import display
print("Beberapa baris pertama tabel sesi-per-host:")
display(wide_df.head(10))

Beberapa baris pertama tabel sesi-per-host:

,host,Sesi Login,A,B,C,D,E,F,G,H,...,Q,R,S,T,U,V,W,X,Y,Z
0,***.novo.dk,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,***.novo.dk,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,***.novo.dk,2,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,***.novo.dk,3,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,***.novo.dk,4,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
5,001.msy4.communique.net,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,007.thegap.com,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,007.thegap.com,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,007.thegap.com,2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,007.thegap.com,3,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Tabel Kesimpulan

In [20]:
import pandas as pd

# wide_df = tabel host + Sesi Login + kolom2 A..Z
df = wide_df.copy()

# 1. Tentukan kolom fitur (A,B,C,...)
feature_cols = [c for c in df.columns if c not in ["host", "Sesi Login"]]

# 2. Hitung berapa banyak halaman (A..Z) yang dikunjungi di tiap sesi
df["total_visited"] = df[feature_cols].sum(axis=1)

# 3. Untuk tiap host, pilih sesi yang:
#    - total_visited paling besar (kunjungan terbanyak)
#    - kalau seri (imbang), ambil Sesi Login terkecil (paling awal)
best_sessions = (
    df
    .sort_values(["host", "total_visited", "Sesi Login"], ascending=[True, False, True])
    .drop_duplicates(subset="host")   # sisain 1 sesi terbaik per host
)

# 4. Ambil hanya host + pola A..Z
summary_df = best_sessions[["host"] + feature_cols].reset_index(drop=True)

# 5. Simpan ke CSV
output_summary = "tabel_host_sesi_dominan.csv"
summary_df.to_csv(output_summary, sep=",", index=False)

from IPython.display import display
print("Tabel host dengan sesi paling dominan (jumlah kunjungan terbanyak):")
display(summary_df.head(10))

Tabel host dengan sesi paling dominan (jumlah kunjungan terbanyak):

,host,A,B,C,D,E,F,G,H,I,...,Q,R,S,T,U,V,W,X,Y,Z
0,***.novo.dk,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,001.msy4.communique.net,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,007.thegap.com,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,01-dynamic-c.wokingham.luna.net,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,01.ts01.zircon.net.au,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,02-17-05.comsvc.calpoly.edu,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,02-dynamic-c.wokingham.luna.net,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,023.msy4.communique.net,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,03-dynamic-c.wokingham.luna.net,1,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0321jona.jon.rpslmc.edu,1,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Kunjungan Host

In [13]:
import pandas as pd

# pakai dataframe yang sudah ada kolom 'host' dan 'url_code'
df = filtered_df.copy()

# 1. Anggap setiap baris = 1 kunjungan
df["visited"] = 1

# 2. Hilangkan duplikat host+url_code (biar tiap host-url_code cuma sekali)
df_unique = df.drop_duplicates(subset=["host", "url_code"])

# 3. Pivot: 1 baris = 1 host, kolom = A,B,C,... berisi 1/0
host_summary = (
    df_unique
    .pivot_table(
        index="host",          # baris: per host
        columns="url_code",    # kolom: A, B, C, ...
        values="visited",
        aggfunc="max",         # kalau ada, jadinya 1
        fill_value=0           # kalau tidak ada, 0
    )
    .reset_index()
)

# Bersihkan nama level kolom bawaan pivot_table
host_summary.columns.name = None

# 4. Simpan ke CSV
output_host = "tabel_total_kunjungan_per_host.csv"
host_summary.to_csv(output_host, sep=",", index=False)

from IPython.display import display
print("Beberapa baris pertama total kunjungan per host:")
display(host_summary.head(10))

Beberapa baris pertama total kunjungan per host:

,host,A,B,C,D,E,F,G,H,I,...,Q,R,S,T,U,V,W,X,Y,Z
0,***.novo.dk,1,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,001.msy4.communique.net,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,007.thegap.com,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,01-dynamic-c.wokingham.luna.net,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
4,01.ts01.zircon.net.au,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,02-17-05.comsvc.calpoly.edu,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,02-dynamic-c.wokingham.luna.net,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,023.msy4.communique.net,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,03-dynamic-c.wokingham.luna.net,1,1,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
9,0321jona.jon.rpslmc.edu,1,1,1,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0